name: Build and Deploy to EC2

on:
  push:
    branches:
      - feature/delivery-orders

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Rename Spring Boot JAR to new-parcel.jar
        run: |
          JAR_FILE=$(find target -maxdepth 1 -type f -name "*.jar" ! -name "*original*" ! -name "*plain*" | head -n 1 | tr -d '\r\n')
          echo "Using JAR: $JAR_FILE"
          if [ -z "$JAR_FILE" ]; then
          echo "No JAR file found to rename!"
          exit 1
          fi
          mv "$JAR_FILE" target/new-parcel.jar
      

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/new-parcel.jar"
          target: "/home/ubuntu/backend/new-parcel.jar"

      - name: Trigger Deploy Script on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/backend
            chmod +x deploy.sh
            bash deploy.sh
